version: 0.1.{build}
os: Visual Studio 2015
branches:
  # whitelist
  only:
    - master
skip_tags: true
test:
  assemblies:
    - Michi.Test.dll
configuration:
  - Debug
  - Release
# Fix line endings on Windows
init:
  - git config --global core.autocrlf true
build:
  project: Michi.sln
  parallel: true
  
cache:
  - packages -> **\packages.config
  
install:
    - nuget update -self
    - nuget install OpenCover -ExcludeVersion
    - nuget install xunit.runner.console -Version 2.1.0
    - nuget restore ./Michi.sln

test_script:
    - rem Running Tests...
    - OpenCover\tools\OpenCover.Console.exe -register:user -target:"xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"Michi.Tests\bin\%CONFIGURATION%\Michi.Tests.dll -noshadow -appveyor" -output:coverage.xml
after_test:
    - rem Uploading Code Coverage Report to Codecov...
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "coverage.xml"

artifacts:
    - path: Michi\bin\$(configuration)
      name: Michi
      type: zip