version: 0.1.{build}
os: Visual Studio 2015
branches:
  # whitelist
  only:
    - master
skip_tags: true
test:
  assemblies:
    - Michi.Test.dll
configuration:
  - Debug
  - Release
# Fix line endings on Windows
init:
  - git config --global core.autocrlf true
build:
  project: Michi.sln
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
  
cache:
  - packages -> **\packages.config
  
install:
    - nuget update -self
    - nuget install OpenCover -ExcludeVersion
    - nuget install xunit.runner.console -Version 2.1.0
    - nuget restore ./Michi.sln

test_script:
    - rem Running Tests...
    - OpenCover\tools\OpenCover.Console.exe -register:user -target:"xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"Michi.Tests\bin\%CONFIGURATION%\Michi.Tests.dll -noshadow -appveyor" -output:coverage.xml
after_test:
    - rem Uploading Code Coverage Report to Codecov...
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "coverage.xml"
    - rem Packing NuGet packages...
    - nuget pack Michi\Michi.csproj -IncludeReferencedProjects -Symbols

artifacts:
    - path: Michi\bin\$(configuration)
      name: Michi
      type: zip
    - path: 'Michi.nupkg'
      name: Michi NuGet Packages

deploy:
    - provider: NuGet
      server: https://www.myget.org/F/snowflake-nightly/api/v2/package
      api_key:
        secure: c0TSni4oM3D75P31isNFRu0z4whPsrvTAcu67iLlFmtvvrzopEI8Xj5qWk1pwMkj
      symbol_server: https://nuget.symbolsource.org/MyGet/snowflake-nightly
      skip_symbols: false
